// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU8mZUQHrXG3xb99s6wo_wHOSXfaDRMKY',
    appId: '1:182105393508:web:eee26aea9d87c35ac9d271',
    messagingSenderId: '182105393508',
    projectId: 'employeelogin-cc037',
    authDomain: 'employeelogin-cc037.firebaseapp.com',
    storageBucket: 'employeelogin-cc037.firebasestorage.app',
    measurementId: 'G-38TDF13XQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5IK4qDIqgbwPeaQnvhWAEV8Wh07K1GJU',
    appId: '1:182105393508:android:1cf4dbd49b8e099ec9d271',
    messagingSenderId: '182105393508',
    projectId: 'employeelogin-cc037',
    storageBucket: 'employeelogin-cc037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-GPe1-n_ga98Dz3pp9xlIxVpMrFBimHQ',
    appId: '1:182105393508:ios:0cda8dbd65a6371ac9d271',
    messagingSenderId: '182105393508',
    projectId: 'employeelogin-cc037',
    storageBucket: 'employeelogin-cc037.firebasestorage.app',
    androidClientId: '182105393508-a10op83ubvumn4uk09qeru8g0nbbd25e.apps.googleusercontent.com',
    iosClientId: '182105393508-505ha3pejb9tkmjl65lgeenebslhhg20.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonEmissionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-GPe1-n_ga98Dz3pp9xlIxVpMrFBimHQ',
    appId: '1:182105393508:ios:0cda8dbd65a6371ac9d271',
    messagingSenderId: '182105393508',
    projectId: 'employeelogin-cc037',
    storageBucket: 'employeelogin-cc037.firebasestorage.app',
    androidClientId: '182105393508-a10op83ubvumn4uk09qeru8g0nbbd25e.apps.googleusercontent.com',
    iosClientId: '182105393508-505ha3pejb9tkmjl65lgeenebslhhg20.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonEmissionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU8mZUQHrXG3xb99s6wo_wHOSXfaDRMKY',
    appId: '1:182105393508:web:a22583b4d1b23a96c9d271',
    messagingSenderId: '182105393508',
    projectId: 'employeelogin-cc037',
    authDomain: 'employeelogin-cc037.firebaseapp.com',
    storageBucket: 'employeelogin-cc037.firebasestorage.app',
    measurementId: 'G-53MB0QXJWD',
  );

}